export interface StickerProps {
	id: string;
	text: string;
}

export const HERO_TITLES: string[][] = [
	[
		"FINALLY YOU HAVE A CHANCE TO CAUSE ",
		"PUBLIC CONFUSION BY BUYING SOMETHING ",
		"COMPLETELY USELESS.",
	],
	["Let Us Introduce The Stickers ", "You Never Knew You Didn’t Need."],
	["Every Single One Of Them ", "Is Pointless, Useless, and", " We Are Not Even Proud Of It."],
	["Some Say They’re Greatly Overpriced... ", "But Honestly—Why Not...?"],
	["Satisfaction? Who Needs It? ", "We are famous for zero ", "satisfaction guarantee."],
	["With our stickers we strive ", "to be Annoying, Ridiculous", "and Completely Irresistible."],
	[
		"You can now make a complete fool ",
		" of yourself By Turning Any Object into ",
		" a Joke That Nobody Gets.",
	],
	["Now get yourself together. ", "Buy now and overthink later."],
];

export const ABOUT = [
	{
		text: "Completely useless stickers is an evil project by a lazy graphic-designer who doesn’t want to do anything useful to earn money but be completely useless instead. This project embraces the art of doing nothing important while maximizing confusion, awkward moments, and pointless chaos in the world. Each sticker is a deliberate attempt to make everyday objects bewilder you—and make your life a lot less productive.",
	},
	{
		text: "Support this project on kickstarter, not because you need it, but because you secretly love wasting your precious time and hard-earned money on something completely useless.",
	},
	{
		id: "disclaimer",
		text: "P.S. The real reason is that i’ve been in advertising for over 20 years, I hate advertising and all the fake stuff that i have had to do for it. so i have always wanted to make and write complete parody of modern advertising.",
	},
];

export const STICKERS: StickerProps[] = [
	{ id: "vuuz", text: "IN CASE OF EMERGENCY BREAK THIS WALL TO ESCAPE" },
	{ id: "egio", text: "WHAT HAPPENS IN THIS BATH-ROOM, STAYS IN THIS BATH-ROOM." },
	{ id: "mpht", text: "UNDER NO CIRCUMSTANCES OPEN THE DOOR TO THIS SECRET CHAMBER." },
	{ id: "qetw", text: "I WONDER WHY COFFEE TASTES SO GOOD WHEN I AM NAKED" },
	{ id: "yyoc", text: "USE THIS DOOR. OR TRY FINDING AN-OTHER DOOR" },
	{ id: "afdm", text: "CHOOSE A DOOR WISELY..." },
	{ id: "flsc", text: "PLEASE NOTICE THIS STICKER. IT IS IMPORTANT" },
	{ id: "tpgs", text: "WARNING! YOU CAN READ." },
	{ id: "ndjo", text: "THIS THING WILL HAPPEN TO YOU AGAIN AND AGAIN" },
	{ id: "esum", text: "THIS IS A NICE SPOT FOR SUCH A GOOD STICKER LIKE MYSELF" },
	{ id: "rwtc", text: "WE WILL NEVER GET OUT OF HERE ALIVE" },
	{ id: "vvfa", text: "PLEASE DO NOT FEED THESE ANIMALS!" },
	{ id: "bxlk", text: "IN CASE OF EMERGENCY WALK FAST AND LOOK SCARED." },
	{ id: "wodm", text: "IF YOU NEED HELP PLEASE YELL AND CAUSE PANIC." },
	{ id: "nlhg", text: "LEAVE NOW OR RISK STAYING." },
	{ id: "wgvz", text: "PLEASE CLOSE THIS DOOR. OR LEAVE IT OPEN. WE DON’T CARE" },
	{ id: "xvce", text: "DO NOT LOOK DIRECTLY INTO THE EYES OF OUR PERSONNEL." },
	{ id: "xyzr", text: "PLEASE WASH ONLY YOUR OWN HANDS!" },
	{ id: "otjr", text: "PLEASE NOT NOW! UNLESS YOU ARE A REBEL" },
	{ id: "hagm", text: "IT IS STRICTLY FORBIDDEN TO PUT ANY STICKERS ON THIS WALL." },
	{ id: "arvl", text: "PUSH! IF PUSHING DOESN’T WORK THEN TRY PULLING." },
	{ id: "xjug", text: "IN CASE OF EMERGENCY LICK THIS STICKER TO ESCAPE." },
	{ id: "ybkn", text: "CONGRATULATIONS! YOU HAVE FOUND THE DOOR." },
	{ id: "vzhh", text: "SORRY IF I SEEM SAD AND DEPRESSED. I’M JUST A STICKER." },
	{ id: "mvay", text: "WARNING. THIS TOILET PAPER MIGHT MAKE YOU MORE HAPPY THAN IT SHOULD." },
	{ id: "eood", text: "INSTRUCTIONS ON THIS STICKER CAN BE MISLEADING" },
	{ id: "dlgl", text: "ONLY PROCEED IF YOU DIDN’T READ THIS" },
	{ id: "uwgb", text: "THIS TELEPORTATION DEVICE IS TEMPORARILY OUT OF SERVICE." },
	{ id: "tnpg", text: "TO TELEPORT PLEASE PUT BOTH HANDS HERE AND WAIT" },
	{ id: "jiyp", text: "PULL! IF PULLING DOESN’T WORK THEN TRY PUSHING." },
	{ id: "fnzm", text: "PLEASE DO NOT LICK PEOPLE IN THIS ROOM. UNLESS THEY ASK FOR IT" },
	{ id: "drks", text: "DO NOT TRUST THE INSTRUCTIONS ON THIS STICKER" },
	{ id: "wwqj", text: "THERE’S NO ESCAPE. STOP SEARCHING." },
	{ id: "huyi", text: "DO NOT LICK THIS STICKER FOR LONGER THAN 10 SECONDS" },
	{ id: "uazl", text: "PRESSING THIS BUTTON CAN CHANGE THINGS AROUND YOU" },
	{ id: "zlnj", text: "DO NOT ATTEMPT TO LEAVE!" },
	{ id: "wqno", text: "PLEASE PRETEND TO BE SANE FOR THE NEXT 8 HOURS. THANK YOU" },
	{ id: "fsud", text: "THINK OF SOMETHING SAD LIKE A BABY SHARK BEING EATEN BY A KITTEN" },
	{ id: "wflp", text: "DO NOT FEED OUR STAFF!" },
	{ id: "ztdm", text: "CONGRATULATIONS! YOU’VE FOUND THIS STICKER" },
	{ id: "ytat", text: "OPEN T-HIS DOOR BEFORE ENTERING. THANK YOU!" },
	{ id: "umsv", text: "DO NOT OPEN! OR OPEN. WE DON’T CARE" },
	{ id: "fnyu", text: "ATTENTION! BEWARE OF SURPRISES" },
	{ id: "wzxq", text: "THIS OBJECT UNDERSTANDS YOU" },
	{ id: "yzjp", text: "OH, IT’S YOU AGAIN..." },
	{ id: "bgrm", text: "HITTING THIS THING WITH YOUR HEAD CAN RESULT IN PAIN" },
	{ id: "ukrz", text: "THIS OBJECT WOULD BE WORKING IF IT WAS NOT BROKEN" },
	{ id: "mwqf", text: "DO NOT LICK THIS MIRROR. GO LICK YOUR OWN MIRROR" },
	{ id: "wqck", text: "BE STRONG. OPEN THIS DOOR WITHOUT YOUR HANDS" },
	{ id: "knul", text: "PLEASE WAIT UNTIL SOMEONE COMES AND EXPLAINS THIS" },
	{ id: "yufm", text: "PLEASE ONLY LICK THIS THING IF YOU ACTUALLY ENJOY IT." },
	{ id: "ugwp", text: "PLEASE PREPARE YOUR BODY FOR THE UPCOMING EVENTS." },
	{ id: "hltq", text: "DO NOT TRUST ANY STICKERS AROUND HERE! THEY’RE LYING." },
	{ id: "uujr", text: "BEING DELICIOUS IS NOT EVERYTHING" },
	{ id: "ywfr", text: "PLEASE WAIT HERE UNTIL I HAVE TIME FOR YOUR BULLSHIT" },
	{ id: "zbpq", text: "YOUR BULLSHIT IS VERY IMPORTANT TO US!" },
	{ id: "xwen", text: "DO NOT LOOK UP. OR LOOK. WE DON’T CARE." },
	{ id: "bdve", text: "CALM YOUR MIND AND LISTEN TO A STICKER SINGING" },
	{ id: "yaqs", text: "PLEASE DO NOT ARGUE WITH THIS STICKER" },
	{ id: "scaw", text: "DO NOT STAND DIRECTLY UNDER OUR WIFI. THANK YOU!" },
	{ id: "uwss", text: "PLEASE DO NOT MAKE ANY CONFUSED NOISE." },
	{ id: "sjwi", text: "CONSULT WITH THIS STICKER IF YOU NEED ASSISTANCE" },
	{ id: "jjce", text: "WE’D LOVE TO HELP YOU BUT AT THE MOMENT WE DON’T WANT TO" },
	{ id: "jyzi", text: "NOT THIS STICKER AGAIN" },
	{ id: "hybo", text: "PLEASE URINATE HERE WITH STYLE AND SOPHISTICATION" },
	{ id: "ypse", text: "DO NOT ALARM THIS DOOR. IT COULD BE SLEEPING" },
	{ id: "rtea", text: "PLEASE ACKNOWLEDGE THAT THIS USELESS STICKER IS USELESS" },
	{ id: "jvgm", text: "PLEASE DO NOT CONFUSE THIS VODKA CONTAINER FOR WATER" },
	{ id: "uweo", text: "IN CASE OF WORK OVERLOAD OPEN THESE SELF DESTRUCTION DOORS" },
	{ id: "eklf", text: "IN CASE OF A WET FLOOR PLEASE KEEP CALM AND SWIM TO SAFETY" },
];

export const TOP_10_STICKERS: StickerProps[] = [
	{ id: "xjug", text: "IN CASE OF EMERGENCY LICK THIS STICKER TO ESCAPE." },
	{ id: "ypse", text: "DO NOT ALARM THIS DOOR. {{br}}IT COULD BE SLEEPING." },
	{ id: "ybkn", text: "CONGRATULATIONS! YOU HAVE {{br}}FOUND THE DOOR." },
	{ id: "ywfr", text: "PLEASE WAIT HERE UNTIL I HAVE {{br}}TIME FOR YOUR BULLSHIT." },
	{ id: "fnzm", text: "PLEASE DO NOT LICK PEOPLE IN THIS ROOM. UNLESS THEY ASK FOR IT." },
	{ id: "fsud", text: "THINK OF SOMETHING SAD LIKE A BABY SHARK BEING EATEN BY A KITTEN." },
	{ id: "eklf", text: "IN CASE OF A WET FLOOR PLEASE KEEP CALM AND SWIM TO SAFETY." },
	{ id: "eood", text: "INSTRUCTIONS ON THIS STICKER CAN BE MISLEADING." },
	{ id: "bdve", text: "CALM YOUR MIND AND LISTEN TO A STICKER SINGING." },
];

export const GPT_STICKERS: StickerProps[] = [
	{ id: "XRCJ", text: "THIS SPACE RESERVED FOR INVISIBLE CARS." },
	{ id: "YWBD", text: "PLEASE DO NOT ARGUE WITH THIS SIGN. IT ALWAYS WINS." },
	{ id: "OGZT", text: "IN CASE OF DOUBT, BLAME THE PERSON BEHIND YOU." },
	{ id: "VKLO", text: "THIS WALL IS CURRENTLY OUT OF ORDER." },
	{ id: "CZMT", text: "FOR MAXIMUM EFFECT, READ THIS SIGN LOUDLY." },
	{ id: "JVFB", text: "WARNING: SENSE OF HUMOR REQUIRED BEYOND THIS POINT." },
	{ id: "NXTU", text: "IF LOST, FOLLOW YOUR INSTINCTS (OR THIS SIGN)." },
	{ id: "PYGN", text: "TOUCHING THIS SIGN WILL GIVE YOU SUPERPOWERS. MAYBE." },
	{ id: "QVEK", text: "DO NOT CROSS THIS LINE UNLESS YOU LIKE LINES." },
	{ id: "ZWXM", text: "THIS SIGN IS ON VACATION. PLEASE COME BACK LATER." },
	{ id: "UOAK", text: "BEWARE OF SHADOWS. THEY’RE UP TO SOMETHING." },
	{ id: "LYFM", text: "THIS IS A COMPLAINT BOX. PLEASE YELL INTO IT." },
	{ id: "QYHZ", text: "DANGER: THIS OBJECT MAY BE HAVING AN IDENTITY CRISIS." },
	{ id: "MLWR", text: "PLEASE STAND HERE FOR NO PARTICULAR REASON." },
	{ id: "YOLK", text: "WARNING: THIS SIGN IS WATCHING YOU BACK." },
	{ id: "FZUT", text: "DO NOT BREATHE TOO LOUDLY NEAR THIS STICKER." },
	{ id: "WGKN", text: "FOR EMERGENCY ADVICE, ASK THE NEAREST DOG." },
	{ id: "KHYO", text: "THIS SIGN HAS NOTHING IMPORTANT TO SAY." },
	{ id: "VLEQ", text: "DO NOT READ THIS SIGN WHILE OPERATING HEAVY MACHINERY." },
	{ id: "ZTWA", text: "CAUTION: STANDING HERE MAY LEAD TO LIFE DECISIONS." },
	{ id: "LMRE", text: "YOU ARE NOW ENTERING A ZONE OF ABSURDITY." },
	{ id: "HPXS", text: "WARNING: SMILING NEAR THIS SIGN IS STRICTLY ENCOURAGED." },
	{ id: "WYSJ", text: "PLEASE REPORT ALL SUSPICIOUS SHAPES TO THIS STICKER." },
	{ id: "RCYB", text: "THIS IS A DESIGNATED SIGHING AREA." },
	{ id: "BRVX", text: "CAUTION: THIS SURFACE IS NOT A TRAMPOLINE (BUT GO AHEAD)." },
	{ id: "QLMK", text: "DO NOT OPEN THIS DOOR UNLESS YOU WANT TO GO THROUGH IT." },
	{ id: "JWOQ", text: "THIS SIGN BELIEVES IN YOU. DON’T LET IT DOWN." },
	{ id: "HZWN", text: "WARNING: READING THIS SIGN MAY CAUSE CONFUSION." },
	{ id: "VZRK", text: "STANDING HERE MAKES YOU LOOK COOL. TRUST US." },
	{ id: "NPYT", text: "IF YOU’RE READING THIS, YOU’VE ALREADY WON." },
	{ id: "LRGT", text: "DO NOT TOUCH THIS. IT HAS NO REASON TO BE TOUCHED." },
	{ id: "QPZN", text: "THIS FLOOR IS NOT A TRAMPOLINE. BUT WE DARE YOU." },
	{ id: "XWUC", text: "IN CASE OF FUN, PLEASE REPORT TO MANAGEMENT." },
	{ id: "KTPY", text: "WARNING: OBJECTS IN MIRROR MAY BE UGLIER THAN THEY APPEAR." },
	{ id: "MHLX", text: "IF YOU CAN READ THIS, YOU'RE TOO CLOSE." },
	{ id: "VNZR", text: "THIS IS A TIME MACHINE. IT ONLY GOES FORWARD." },
	{ id: "TWJH", text: "PUSH THIS WALL TO TEST YOUR STRENGTH." },
	{ id: "HRKC", text: "THIS IS NOT A WINDOW. STOP STARING." },
	{ id: "YZXM", text: "WARNING: THIS HANDLE MAY HANDLE YOU BACK." },
	{ id: "GQPR", text: "IN CASE OF BOREDOM, READ THIS SIGN AGAIN." },
	{ id: "KLMB", text: "THIS IS A DESIGNATED STARING AREA. PLEASE STARE RESPONSIBLY." },
	{ id: "RFWZ", text: "CONGRATULATIONS, YOU FOUND NOTHING!" },
	{ id: "BXJH", text: "THIS STICKER IS SHY. PLEASE DO NOT LOOK DIRECTLY AT IT." },
	{ id: "CWPL", text: "OPEN THIS DOOR SLOWLY. IT HAS FEELINGS." },
	{ id: "PLRH", text: "NOTICE: THIS NOTICE SERVES NO PURPOSE." },
	{ id: "NKSV", text: "PLEASE DO NOT BREATHE IN THIS VICINITY. WE NEED THE AIR." },
	{ id: "TVNM", text: "THIS WALL IS EXPERIENCING A MID-LIFE CRISIS. BE KIND." },
	{ id: "WGBR", text: "WARNING: EXTREME CURIOSITY MAY OCCUR IF YOU READ THIS SIGN." },
	{ id: "DKSY", text: "DO NOT STAND HERE. OR DO. WE’RE NOT YOUR BOSS." },
	{ id: "HQML", text: "PRESS THIS BUTTON FOR A MILD SENSE OF ACCOMPLISHMENT." },
	{ id: "RZWT", text: "IN CASE OF CONFUSION, REMAIN CONFUSED." },
	{ id: "YXHL", text: "THIS IS NOT A REAL SIGN. PLEASE IGNORE." },
	{ id: "KLVN", text: "BEWARE OF THE DOOR. IT KNOWS TOO MUCH." },
	{ id: "MFWJ", text: "THIS STICKER IS LONELY. SAY HELLO." },
	{ id: "ZQLP", text: "STAND HERE TO INCREASE YOUR COOLNESS BY 0.2%." },
	{ id: "WYKV", text: "WARNING: THIS IS AN OVERLY DRAMATIC STICKER." },
	{ id: "TFNP", text: "THIS MIRROR MAY CONTAIN YOUR WORST ENEMY." },
	{ id: "BXQW", text: "YOU ARE NOW LEAVING YOUR COMFORT ZONE. WELCOME BACK." },
	{ id: "NLYH", text: "PRESS THIS FOR A SURPRISE. NO REFUNDS IF THERE’S NONE." },
	{ id: "FZWT", text: "PLEASE ENJOY THE NOTHINGNESS THIS SIGN PROVIDES." },
	{ id: "HJQL", text: "CAUTION: THIS CORNER IS SHARPER THAN YOUR WIT." },
	{ id: "PVMG", text: "PLEASE KEEP ALL LOOSE THOUGHTS SECURELY FASTENED." },
	{ id: "QYJN", text: "DO NOT LET THIS SIGN RUIN YOUR DAY. OR DO." },
	{ id: "MTPX", text: "THIS IS A JUDGMENT-FREE ZONE. EXCEPT FOR THIS SIGN." },
	{ id: "NRCV", text: "WARNING: THIS STICKER MAY CONTAIN TRACE AMOUNTS OF SARCASM." },
	{ id: "WTVZ", text: "PLEASE REFRAIN FROM STARING AT THIS SIGN FOR TOO LONG." },
	{ id: "LKMX", text: "PRESS HERE TO FEEL LIKE YOU DID SOMETHING TODAY." },
	{ id: "ZHRB", text: "THIS SIGN DOES NOT GUARANTEE HAPPINESS, BUT IT DOESN’T HURT." },
	{ id: "PLKJ", text: "DO NOT FEED THE INSECURITIES OF THIS SIGN." },
	{ id: "XNLY", text: "THIS WALL HAS HEARD ALL YOUR SECRETS." },
	{ id: "BQWM", text: "PLEASE KEEP YOUR EXPECTATIONS LOW AROUND THIS SIGN." },
	{ id: "RCZV", text: "STANDING HERE MAKES YOU INVISIBLE TO YOUR RESPONSIBILITIES." },
	{ id: "KLJG", text: "WARNING: THIS SIGN IS PROBABLY WASTING YOUR TIME." },
	{ id: "FNXY", text: "PLEASE CONSULT A CAT BEFORE TAKING ANY MAJOR LIFE DECISIONS." },
	{ id: "TVHX", text: "DO NOT POKE THIS SIGN. IT’S VERY TICKLISH." },
	{ id: "HRJP", text: "CAUTION: THIS WALL MAY HAVE TRUST ISSUES." },
	{ id: "NYPV", text: "FOR BEST RESULTS, DO THE OPPOSITE OF WHAT THIS SIGN SAYS." },
	{ id: "GXRV", text: "THIS SIGN IS LOST. PLEASE RETURN TO ITS RIGHTFUL OWNER." },
	{ id: "BMZX", text: "WARNING: THIS STICKER MAY CAUSE UNCONTROLLABLE EYE ROLLING." },
	{ id: "PQJL", text: "THIS SIGN BELIEVES IN YOU, EVEN IF NO ONE ELSE DOES." },
	{ id: "WRFM", text: "DO NOT STAND HERE UNLESS YOU ENJOY BEING MEDIOCRE." },
];
