export const HERO_TITLES = [
  [
    "FINALLY YOU HAVE A CHANCE TO CAUSE ",
    "PUBLIC CONFUSION BY BUYING SOMETHING ",
    "COMPLETELY USELESS.",
  ],
  ["Let Us Introduce The Stickers ", "You Never Knew You Didn’t Need."],
  ["Every Single One Of Them ", "Is Pointless, Useless, and", " We Are Even Proud Of It."],
  ["Some Say They’re Greatly Overpriced... ", "But Honestly—Why Not...?"],
  ["Satisfaction? Who Needs It? ", "We are famous for zero ", "satisfaction guarantee."],
  ["With our stickers we strive ", "to be Annoying, Ridiculous", "and Completely Irresistible."],
  [
    "You can now make a complete fool ",
    " of yourself By Turning Any Object into ",
    " a Joke That Nobody Gets.",
  ],
  ["Now get yourself together. ", "Buy now and overthink later."],
];

export const ABOUT = [
  {
    text: "Completely useless stickers is an evil project by a lazy graphic-designer who doesn’t want to do anything useful to earn money but be completely useless instead. This project embraces the art of doing nothing important while maximizing confusion, awkward moments, and pointless chaos in the world. Each sticker is a deliberate attempt to make everyday objects bewilder you—and make your life a lot less productive.",
  },
  {
    text: "Support this project on kickstarter, not because you need it, but because you secretly love wasting your precious time and hard-earned money on something completely useless.",
  },
  {
    id: "disclaimer",
    text: "P.S. The real reason is that i’ve been in advertising for over 20 years, I hate advertising and all the fake stuff that i have had to do for it. so i have always wanted to make and write complete parody of modern advertising.",
  },
];

export const STICKERS = [
  { id: "vuuz", text: "IN CASE OF EMERGENCY BREAK THIS WALL TO ESCAPE" },
  { id: "egio", text: "WHAT HAPPENS IN THIS BATH-ROOM, STAYS IN THIS BATH-ROOM." },
  { id: "mpht", text: "UNDER NO CIRCUMSTANCES OPEN THE DOOR TO THIS SECRET CHAMBER." },
  { id: "qetw", text: "I WONDER WHY COFFEE TASTES SO GOOD WHEN I AM NAKED" },
  { id: "yyoc", text: "USE THIS DOOR. OR TRY FINDING AN-OTHER DOOR" },
  { id: "afdm", text: "CHOOSE A DOOR WISELY..." },
  { id: "flsc", text: "PLEASE NOTICE THIS STICKER. IT IS IMPORTANT" },
  { id: "tpgs", text: "WARNING! YOU CAN READ." },
  { id: "ndjo", text: "THIS THING WILL HAPPEN TO YOU AGAIN AND AGAIN" },
  { id: "esum", text: "THIS IS A NICE SPOT FOR SUCH A GOOD STICKER LIKE MYSELF" },
  { id: "rwtc", text: "WE WILL NEVER GET OUT OF HERE ALIVE" },
  { id: "vvfa", text: "PLEASE DO NOT FEED THESE ANIMALS!" },
  { id: "bxlk", text: "IN CASE OF EMERGENCY WALK FAST AND LOOK SCARED." },
  { id: "wodm", text: "IF YOU NEED HELP PLEASE YELL AND CAUSE PANIC." },
  { id: "nlhg", text: "LEAVE NOW OR RISK STAYING." },
  { id: "wgvz", text: "PLEASE CLOSE THIS DOOR. OR LEAVE IT OPEN. WE DON’T CARE" },
  { id: "xvce", text: "DO NOT LOOK DIRECTLY INTO THE EYES OF OUR PERSONNEL." },
  { id: "xyzr", text: "PLEASE WASH ONLY YOUR OWN HANDS!" },
  { id: "otjr", text: "PLEASE NOT NOW! UNLESS YOU ARE A REBEL" },
  { id: "hagm", text: "IT IS STRICTLY FORBIDDEN TO PUT ANY STICKERS ON THIS WALL." },
  { id: "arvl", text: "PUSH! IF PUSHING DOESN’T WORK THEN TRY PULLING." },
  { id: "xjug", text: "IN CASE OF EMERGENCY LICK THIS STICKER TO ESCAPE." },
  { id: "ybkn", text: "CONGRATULATIONS! YOU HAVE FOUND THE DOOR." },
  { id: "vzhh", text: "SORRY IF I SEEM SAD AND DEPRESSED. I’M JUST A STICKER." },
  { id: "mvay", text: "WARNING. THIS TOILET PAPER MIGHT MAKE YOU MORE HAPPY THAN IT SHOULD." },
  { id: "eood", text: "INSTRUCTIONS ON THIS STICKER CAN BE MISLEADING" },
  { id: "dlgl", text: "ONLY PROCEED IF YOU DIDN’T READ THIS" },
  { id: "uwgb", text: "THIS TELEPORTATION DEVICE IS TEMPORARILY OUT OF SERVICE." },
  { id: "tnpg", text: "TO TELEPORT PLEASE PUT BOTH HANDS HERE AND WAIT" },
  { id: "jiyp", text: "PULL! IF PULLING DOESN’T WORK THEN TRY PUSHING." },
  { id: "fnzm", text: "PLEASE DO NOT LICK PEOPLE IN THIS ROOM. UNLESS THEY ASK FOR IT" },
  { id: "drks", text: "DO NOT TRUST THE INSTRUCTIONS ON THIS STICKER" },
  { id: "wwqj", text: "THERE’S NO ESCAPE. STOP SEARCHING." },
  { id: "huyi", text: "DO NOT LICK THIS STICKER FOR LONGER THAN 10 SECONDS" },
  { id: "uazl", text: "PRESSING THIS BUTTON CAN CHANGE THINGS AROUND YOU" },
  { id: "zlnj", text: "DO NOT ATTEMPT TO LEAVE!" },
  { id: "wqno", text: "PLEASE PRETEND TO BE SANE FOR THE NEXT 8 HOURS. THANK YOU" },
  { id: "fsud", text: "THINK OF SOMETHING SAD LIKE A BABY SHARK BEING EATEN BY A KITTEN" },
  { id: "wflp", text: "DO NOT FEED OUR STAFF!" },
  { id: "ztdm", text: "CONGRATULATIONS! YOU’VE FOUND THIS STICKER" },
  { id: "ytat", text: "OPEN T-HIS DOOR BEFORE ENTERING. THANK YOU!" },
  { id: "umsv", text: "DO NOT OPEN! OR OPEN. WE DON’T CARE" },
  { id: "fnyu", text: "ATTENTION! BEWARE OF SURPRISES" },
  { id: "wzxq", text: "THIS OBJECT UNDERSTANDS YOU" },
  { id: "yzjp", text: "OH, IT’S YOU AGAIN..." },
  { id: "bgrm", text: "HITTING THIS THING WITH YOUR HEAD CAN RESULT IN PAIN" },
  { id: "ukrz", text: "THIS OBJECT WOULD BE WORKING IF IT WAS NOT BROKEN" },
  { id: "mwqf", text: "DO NOT LICK THIS MIRROR. GO LICK YOUR OWN MIRROR" },
  { id: "wqck", text: "BE STRONG. OPEN THIS DOOR WITHOUT YOUR HANDS" },
  { id: "knul", text: "PLEASE WAIT UNTIL SOMEONE COMES AND EXPLAINS THIS" },
  { id: "yufm", text: "PLEASE ONLY LICK THIS THING IF YOU ACTUALLY ENJOY IT." },
  { id: "ugwp", text: "PLEASE PREPARE YOUR BODY FOR THE UPCOMING EVENTS." },
  { id: "hltq", text: "DO NOT TRUST ANY STICKERS AROUND HERE! THEY’RE LYING." },
  { id: "uujr", text: "BEING DELICIOUS IS NOT EVERYTHING" },
  { id: "ywfr", text: "PLEASE WAIT HERE UNTIL I HAVE TIME FOR YOUR BULLSHIT" },
  { id: "zbpq", text: "YOUR BULLSHIT IS VERY IMPORTANT TO US!" },
  { id: "xwen", text: "DO NOT LOOK UP. OR LOOK. WE DON’T CARE." },
  { id: "bdve", text: "CALM YOUR MIND AND LISTEN TO A STICKER SINGING" },
  { id: "yaqs", text: "PLEASE DO NOT ARGUE WITH THIS STICKER" },
  { id: "scaw", text: "DO NOT STAND DIRECTLY UNDER OUR WIFI. THANK YOU!" },
  { id: "uwss", text: "PLEASE DO NOT MAKE ANY CONFUSED NOISE." },
  { id: "sjwi", text: "CONSULT WITH THIS STICKER IF YOU NEED ASSISTANCE" },
  { id: "jjce", text: "WE’D LOVE TO HELP YOU BUT AT THE MOMENT WE DON’T WANT TO" },
  { id: "jyzi", text: "NOT THIS STICKER AGAIN" },
  { id: "hybo", text: "PLEASE URINATE HERE WITH STYLE AND SOPHISTICATION" },
  { id: "ypse", text: "DO NOT ALARM THIS DOOR. IT COULD BE SLEEPING" },
  { id: "rtea", text: "PLEASE ACKNOWLEDGE THAT THIS USELESS STICKER IS USELESS" },
  { id: "jvgm", text: "PLEASE DO NOT CONFUSE THIS VODKA CONTAINER FOR WATER" },
  { id: "uweo", text: "IN CASE OF WORK OVERLOAD OPEN THESE SELF DESTRUCTION DOORS" },
  { id: "eklf", text: "IN CASE OF A WET FLOOR PLEASE KEEP CALM AND SWIM TO SAFETY" },
];

export const TOP_10_STICKERS = [
  { id: "fsud", text: "THINK OF SOMETHING SAD LIKE A BABY SHARK BEING EATEN BY A KITTEN." },
  { id: "ybkn", text: "CONGRATULATIONS! YOU HAVE FOUND THE DOOR." },
  { id: "xjug", text: "IN CASE OF EMERGENCY LICK THIS STICKER TO ESCAPE." },
  { id: "ywfr", text: "PLEASE WAIT HERE UNTIL I HAVE TIME FOR YOUR BULLSHIT." },
  { id: "fnzm", text: "PLEASE DO NOT LICK PEOPLE IN THIS ROOM. UNLESS THEY ASK FOR IT." },
  { id: "ypse", text: "DO NOT ALARM THIS DOOR. IT COULD BE SLEEPING." },
  { id: "eklf", text: "IN CASE OF A WET FLOOR PLEASE KEEP CALM AND SWIM TO SAFETY." },
  { id: "eood", text: "INSTRUCTIONS ON THIS STICKER CAN BE MISLEADING." },
  { id: "bdve", text: "CALM YOUR MIND AND LISTEN TO A STICKER SINGING." },
];
